version: '3'
services:
  pikpakbot:
    image: ghcr.io/finalpi/pikpakautofflinedownloadbot:latest
    container_name: pikpakbot
    restart: always
    env_file:
      - .env
    volumes:
      - ./downloads:/downloads
